apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: private-dns
resources:
- namespace.yaml
- ../external-dns
patches:
- deployment_patch.yaml
- clusterrole_patch.yaml
- clusterrolebinding_patch.yaml
