apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
- ../../bases/flux
- ../../bases/cert-manager
- ../bases/monitoring/kube-prometheus
- ../../bases/monitoring/eck
patchesStrategicMerge:
- flux_patch.yaml
secretGenerator:
- name: alertmanager-main
  namespace: monitoring
  files:
  - alertmanager.yaml
