---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/version: 1.9.7
  name: kube-state-metrics
  namespace: monitoring
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/version: 1.9.7
