apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
- ../../bases/flux
- ../../bases/cert-manager
- ../../bases/linkerd
# - ../bases/monitoring/kube-prometheus
# - ../../bases/monitoring/eck
# - ../bases/microservices-demo
# - ../../bases/ingress-nginx
# - ../../bases/private-dns
# - ../bases/descheduler
patchesStrategicMerge:
- flux_patch.yaml
# - loadgenerator_patch.yaml
# secretGenerator:
# - name: alertmanager-main
#   namespace: monitoring
#   files:
#   - alertmanager.yaml
# - name: azure-creds
#   namespace: private-dns
#   envs:
#   - private-dns.txt
