apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../bases/flux
- ../bases/monitoring/kube-prometheus
- ../../bases/monitoring/eck
- ../bases/microservices-demo
patchesStrategicMerge:
- flux_patch.yaml
- loadgenerator_patch.yaml
