apiVersion: builtin
kind: AnnotationsTransformer
metadata:
  name: notImportantHere
annotations:
  linkerd.io/inject: enabled
fieldSpecs:
- kind: Deployment
  path: spec/template/metadata/annotations
  create: true
