---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-git-config
  namespace: flux
data:
  git.user: juan-lee
  git.email: juan-lee@users.noreply.github.com
  git.url: git@github.com:juan-lee/aks-runtime
  git.branch: staging/region
  git.path: staging/region
  git.label: staging/region
