---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-git-config
  namespace: flux
data:
  git.user: juan-lee
  git.email: juan-lee@users.noreply.github.com
  git.url: git@github.com:juan-lee/aks-runtime
  git.branch: prod/southcentralus
  git.path: prod/southcentralus
  git.label: prod-southcentralus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: flux
spec:
  template:
    spec:
      containers:
      - name: flux
        env:
        - name: SOPS_AZURE_KEYVAULT_URLS
          valueFrom:
            secretKeyRef:
              name: azure-creds
              key: sopsKeyURL
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: azure-creds
              key: clientID
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: azure-creds
              key: tenantID
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azure-creds
              key: clientSecret
