name: 'Deploy Staging'

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'staging/eastus2euap'
      - name: Run a multi-line script
        run: |
          git rebase origin/master
          git push
